//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Log_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveVehicleDB
    {
        public int Id_Vehicle { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string VehicleType { get; set; }
        public string Locations { get; set; }
        public string VehicleModel { get; set; }
        public string TAG { get; set; }
        public string FuelType { get; set; }
        public string ModelYear { get; set; }
        public string Engine { get; set; }
        public string Power { get; set; }
        public string Weight { get; set; }
        public string Color { get; set; }
        public string Responsible { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
