//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Log_MVC
{
    using System;
    using System.Collections.Generic;

    // Esta classe representa o componente model do banco de dados Fuel.
    public partial class Fuel
    {
        public int Id { get; set; }
        public string Fuel_Type { get; set; }
        public string Fuel1 { get; set; }
        public string Density { get; set; }
        public string Nationality { get; set; }
    }
}
