//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicle_Log_MVC
{
    using System;
    using System.Collections.Generic;

    // Esta classe representa o componente model do banco de dados Locations.
    public partial class Locations
    {
        public int Id { get; set; }
        public string Ford_Locations { get; set; }
        public string State { get; set; }
    }
}
