//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehDB
    {
        public int Id_Vehicle { get; set; }
        public string VehicleModel { get; set; }
        public string TAG { get; set; }
        public string Color { get; set; }
        public string FuelType { get; set; }
        public string ModelYear { get; set; }
        public string RegistrationDate { get; set; }
        public string LastUpdate { get; set; }
        public Nullable<int> Id_VehicleTable { get; set; }
    }
}
